apiVersion: v1
kind: Pod
metadata:
  name: resource-allocation
  labels:
    name: resources-nginx
    environment: dev
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  
  resources:
    requests:
      memory: "68Mi"
      cpu: "100m" # 1/10th of cpu
      # provide equal or more than request
    limits:
      memory: "120Mi"
      cpu: "120m"