apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  ## these labels are used to register the pod with service
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  port:
  - containerPort: 80 ### port nginx runs on

