apiVersion: v1
kind: Service
metadata:
  name: service-np
spec:
  type: NodePort
  selector:
    name: roboshop
    environment: dev
    service: demo-np
  ports:
    - port: 80
      targetPort: 80
      