apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    name: roboshop
    service: loadbalncerdemo
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30007